Numpy(Numerical python):

It is used to perform for all operation for array.
Array is used to store items. But only datatypes in array.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
a=np.array([[1,4,8]])
print(a)

[[1 4 8]]


In [4]:
L=[1,4,8]
print(L)

[1, 4, 8]


What is the difference between list and array?

In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
a.ndim

2

In [7]:
b=np.array([12,34,56])
print(b)

[12 34 56]


In [8]:
b.ndim

1

In [9]:
c=np.array([[[1,2,3]],[[4,5,6]]])
print(c)

[[[1 2 3]]

 [[4 5 6]]]


In [10]:
c.ndim

3

In [11]:
x=np.array(['a','b','c'])
print(x)
print(x.ndim)

['a' 'b' 'c']
1


In [12]:
z=np.array([2,5.3,2,4])
print(z)
print(z.ndim)

"""" output
[2.0 5.3 2.0 4.0 ]
"""

[2.  5.3 2.  4. ]
1


'" output\n[2.0 5.3 2.0 4.0 ]\n'

In [13]:
y=np.array([23,56,True,False])
print(y)
print(y.ndim)

[23 56  1  0]
1


In [14]:
a1=np.array([True,56,90.3,5+3j,'a'])
print(a1)                                 
""""Because similar datatype is allowed in array in a1 they have different datatype then the output is same"""

['True' '56' '90.3' '(5+3j)' 'a']


'"Because similar datatype is allowed in array in a1 they have different datatype then the output is same'

To create array use np.array()

In [15]:
#np.zeros()
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [16]:
b=np.zeros([3,5])
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
b.ndim

2

To crate array use np.ones()

In [18]:
c=np.ones(3)         # or  c=np.ones([3])
print(c)
print(c.ndim)

[1. 1. 1.]
1


In [19]:
c=np.ones([3,3])
print(c)
print(c.ndim)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2


To crate array use np.empty()

In [20]:
a=np.empty(0)
print(a)
print(a.ndim)


[]
1


In [21]:
a=np.empty(5)
print(a)
print(a.ndim)

[0. 0. 0. 0. 0.]
1


In [22]:
a=np.empty(0)
a

array([], dtype=float64)

Size function used to count number of elements of the array

In [23]:
a.size

0

To crate array use np.eye()

In [24]:
b=np.eye(4)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


To crate array use np.arange()

In [25]:
c=np.arange(10)
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
c=np.arange(10,20)
print(c)

[10 11 12 13 14 15 16 17 18 19]


In [27]:
c=np.arange(7,15,0.2)
print(c)

[ 7.   7.2  7.4  7.6  7.8  8.   8.2  8.4  8.6  8.8  9.   9.2  9.4  9.6
  9.8 10.  10.2 10.4 10.6 10.8 11.  11.2 11.4 11.6 11.8 12.  12.2 12.4
 12.6 12.8 13.  13.2 13.4 13.6 13.8 14.  14.2 14.4 14.6 14.8]


In [28]:
c=np.arange(10,20,2)
print(c)

[10 12 14 16 18]


In [29]:
c=np.arange(1,10,0.1)
print(c)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5
 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3
 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1
 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]


In [30]:
b=np.arange(1,10)
print(b)
b.ndim

[1 2 3 4 5 6 7 8 9]


1

To create array use np.linspace()


In [31]:
a=np.linspace(10,20)
print(a)

[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]


In [32]:
a=np.linspace(1,10) # it gives by default 50 values from given range
print(a)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [33]:
a=np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [34]:

a=np.linspace(1,10,5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


For change the dimension
resize used.


In [35]:
b=np.arange(1,10)
print(b)
b.ndim

[1 2 3 4 5 6 7 8 9]


1

In [36]:
b.resize((1,10))     # resize used to change the direction
print(b)
print(b.ndim)

[[1 2 3 4 5 6 7 8 9 0]]
2


In [37]:
b=np.arange(3,3)
print(b)
print(b.ndim)

[]
1


In [38]:
b.resize((3,3))     # resize used to change the direction
print(b)
print(b.ndim)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
2


In [39]:
c=np.arange(0,12)
print(c.size)
print(c.ndim)

12
1


In [40]:
c.resize(4,3)
print(c)
print(c.ndim)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
2


In [41]:
b=np.arange(1,5)
print(b)
print(b.ndim)

[1 2 3 4]
1


In [42]:
b.resize(1,1,4)
print(b)

[[[1 2 3 4]]]


In [43]:
z=np.arange(7,15)
print(z)
print(z.ndim)

[ 7  8  9 10 11 12 13 14]
1


In [44]:
z.resize(4,2,8)
print(z)
print(z.ndim)

[[[ 7  8  9 10 11 12 13 14]
  [ 0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0  0  0]
  [ 0  0  0  0  0  0  0  0]]]
3


In [45]:
z.resize(2,2,4)
print(z)
print(z.ndim)

[[[ 7  8  9 10]
  [11 12 13 14]]

 [[ 0  0  0  0]
  [ 0  0  0  0]]]
3


In [46]:
z.resize(2,2,2)
print(z)
print(z.ndim)

[[[ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]]]
3


In [47]:
a=np.arange(10,20)
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [48]:
a.resize(2,6)
print(a)
print(a.ndim)

[[10 11 12 13 14 15]
 [16 17 18 19  0  0]]
2


In [49]:
a.ndim



2

In [50]:
a.shape

(2, 6)

In [51]:
a=np.arange(10,20)
print(a)
a.reshape(1,2,5)

[10 11 12 13 14 15 16 17 18 19]


array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [52]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [53]:
a.tolist()   # convert your array into list is tolist..............................

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [54]:
L=[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
np.array(L)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [55]:
a.tostring() 
#convert your array into string ..............................
# output is in binary string............................

C:\Users\hplap\AppData\Local\Temp\ipykernel_29332\4243426989.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  a.tostring()


b'\n\x00\x00\x00\x0b\x00\x00\x00\x0c\x00\x00\x00\r\x00\x00\x00\x0e\x00\x00\x00\x0f\x00\x00\x00\x10\x00\x00\x00\x11\x00\x00\x00\x12\x00\x00\x00\x13\x00\x00\x00'

In [56]:
L=[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
np.array(L,ndmin=3)

array([[[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]])

In [57]:
a=np.array([1,3,5])
print(a)

[1 3 5]


In [58]:
a[0]=10
print(a)

[10  3  5]


In [59]:
a=np.array([1,3,5])
print("a":a)

SyntaxError: invalid syntax (4198041733.py, line 2)

In [ ]:
b=a.copy()
print(b)
a[0]=1
print(a)

[10  3  5]
[1 3 5]


In [ ]:
import numpy as np
a=np.array([23,34,45])
print(a)

[23 34 45]


In [ ]:
a[1]

34

In [ ]:
b=np.arange(10,20)
print(b)
b.ndim

[10 11 12 13 14 15 16 17 18 19]


1

In [ ]:
b[2:7]

array([12, 13, 14, 15, 16])

In [ ]:
b[2:7:2]

array([12, 14, 16])

In [ ]:
b[-3:-1]

array([17, 18])

In [ ]:
b[0]=100
print(b)

[100  11  12  13  14  15  16  17  18  19]


In [ ]:
np.array([12,23,34],dtype='S')

array([b'12', b'23', b'34'], dtype='|S2')

In [ ]:
np.array([12,23,34],dtype='c')

array([b'1', b'2', b'3'], dtype='|S1')

In [ ]:
np.array([12,23,34],dtype='complex')

array([12.+0.j, 23.+0.j, 34.+0.j])

In [ ]:
np.array([12,23,34],dtype='str')

array(['12', '23', '34'], dtype='<U2')

In [ ]:
np.array([12,23,34],dtype='float')

array([12., 23., 34.])

In [ ]:
a=np.arange(10,22)
print(a)
a.reshape(2,2,3)


[10 11 12 13 14 15 16 17 18 19 20 21]


array([[[10, 11, 12],
        [13, 14, 15]],

       [[16, 17, 18],
        [19, 20, 21]]])

In [ ]:
b=np.arange(1,13)
print(b)
b.reshape(2,2,3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
a+b

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [ ]:
a*b

array([ 10,  22,  36,  52,  70,  90, 112, 136, 162, 190, 220, 252])

In [ ]:
a1=np.arange(1,5)
b1=np.arange(6,10)
print(a1)
print(b1)

[1 2 3 4]
[6 7 8 9]


In [ ]:
a1*b1

array([ 6, 14, 24, 36])

In [ ]:
print(a1-b1)

[-5 -5 -5 -5]


In [ ]:
a1+b1

array([ 7,  9, 11, 13])

In [ ]:
a1-b1

array([-5, -5, -5, -5])

In [ ]:
a1/b1

array([0.16666667, 0.28571429, 0.375     , 0.44444444])

In [ ]:
a1

array([1, 2, 3, 4])

In [ ]:
d1=np.arange(10,100)
d1[d1%2==0]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
b=np.array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
b.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
b.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
b.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
b.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
d=np.array([23,45,67])
print(d)

[23 45 67]


In [ ]:
d.fill(0)

In [ ]:
print(d)

[0 0 0]


In [ ]:
d=np.array([23,45,67])
print(d)
d.fill(100)
print(d)

[100 100 100]


In [ ]:
b=np.array([21,18,15,36,16,25,10,18,42,9,44,0])
b

array([21, 18, 15, 36, 16, 25, 10, 18, 42,  9, 44,  0])

In [ ]:
print("mean of given dataset is:", np.mean(b))

mean of given dataset is: 21.166666666666668


In [ ]:
np.median(b)


18.0

In [ ]:
np.quantile(b,0.25)     #Q1(Quartile 1)

13.75

In [ ]:
np.quantile(b,0.50) #Q3(Quartile 3)

18.0

In [ ]:
np.quantile(b,0.75) #Q3(Quartile 3)

27.75

In [ ]:
np.min(b)

0

In [ ]:
np.max(b)

44

In [ ]:
np.sum(b)

254

In [ ]:
b

array([21, 18, 15, 36, 16, 25, 10, 18, 42,  9, 44,  0])

In [ ]:
np.sort(b)

array([ 0,  9, 10, 15, 16, 18, 18, 21, 25, 36, 42, 44])

In [ ]:
np.sort(b)[::-1]

array([44, 42, 36, 25, 21, 18, 18, 16, 15, 10,  9,  0])

In [ ]:
c=b.reshape(4,3)
c


array([[21, 18, 15],
       [36, 16, 25],
       [10, 18, 42],
       [ 9, 44,  0]])

In [ ]:
c[0]

array([21, 18, 15])

In [ ]:
c[0][1]

18

In [60]:
d=np.array([1,3,0,5,7],ndmin=2)
d


array([[1, 3, 0, 5, 7]])

In [61]:
np.sort(d)[0][::-1]

array([7, 5, 3, 1, 0])

In [ ]:
np.sin(0)

0.0

In [ ]:
np.sin(90)

0.8939966636005579

In [ ]:
np.sin((np.pi)/2)

1.0

In [ ]:
np.pi

3.141592653589793

In [ ]:
print(np.pi)

3.141592653589793


In [ ]:
print(np.e)

2.718281828459045


In [ ]:
print(np.exp(5))

148.4131591025766


In [ ]:
print(np.exp(0))

1.0


In [ ]:
np.cos(0)

1.0

In [ ]:
np.cos((np.pi/2))

6.123233995736766e-17

In [ ]:
np.round(np.cos((np.pi/2)))

0.0

In [ ]:
np.arcsin(0)

0.0

In [ ]:
np.arcsin(1)

1.5707963267948966

In [ ]:
(np.pi/2)

1.5707963267948966

In [ ]:
np.log(0)

C:\Users\hplap\AppData\Local\Temp\ipykernel_16876\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [ ]:
np.log(1)

0.0

In [ ]:
np.log(np.e)

1.0

In [ ]:
np.log10(np.e)

0.4342944819032518

In [ ]:
np.log10(10)

1.0

In [62]:
import numpy as np

In [71]:
a=np.arange(10,106,5)
a.ndim


1

In [68]:
a.shape

(10,)

In [74]:
b=a.reshape(2,2,5)
b

array([[[ 10,  15,  20,  25,  30],
        [ 35,  40,  45,  50,  55]],

       [[ 60,  65,  70,  75,  80],
        [ 85,  90,  95, 100, 105]]])

In [75]:
b.transpose()

array([[[ 10,  60],
        [ 35,  85]],

       [[ 15,  65],
        [ 40,  90]],

       [[ 20,  70],
        [ 45,  95]],

       [[ 25,  75],
        [ 50, 100]],

       [[ 30,  80],
        [ 55, 105]]])

In [81]:
c=np.array ([[ 15,  65],
        [ 40,  90]])

In [82]:
c

array([[15, 65],
       [40, 90]])

In [83]:
c.transpose()

array([[15, 40],
       [65, 90]])